//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKprojekt3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKprojekt3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360,  0.000129900000,  0.000003917000,  0.000606100000
        ///361,  0.000145847000,  0.000004393581,  0.000680879200
        ///362,  0.000163802100,  0.000004929604,  0.000765145600
        ///363,  0.000184003700,  0.000005532136,  0.000860012400
        ///364,  0.000206690200,  0.000006208245,  0.000966592800
        ///365,  0.000232100000,  0.000006965000,  0.001086000000
        ///366,  0.000260728000,  0.000007813219,  0.001220586000
        ///367,  0.000293075000,  0.000008767336,  0.001372729000
        ///368,  0.000329388000,  0.000009839844,  0.001543579000
        ///369,  0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string drugietxt {
            get {
                return ResourceManager.GetString("drugietxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 380	0.0014	0.0000	0.0065
        ///381	0.0015	0.0000	0.0070
        ///382	0.0016	0.0000	0.0077
        ///383	0.0018	0.0001	0.0085
        ///384	0.0020	0.0001	0.0094
        ///385	0.0022	0.0001	0.0105
        ///386	0.0025	0.0001	0.0120
        ///387	0.0029	0.0001	0.0136
        ///388	0.0033	0.0001	0.0155
        ///389	0.0037	0.0001	0.0177
        ///390	0.0042	0.0001	0.0201
        ///391	0.0048	0.0001	0.0225
        ///392	0.0053	0.0002	0.0252
        ///393	0.0060	0.0002	0.0284
        ///394	0.0068	0.0002	0.0320
        ///395	0.0077	0.0002	0.0362
        ///396	0.0088	0.0002	0.0415
        ///397	0.0100	0.0003	0.0473
        ///398	0.0113	0.0003	0.0536
        ///399	0.0128	0.0004	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string faletxt {
            get {
                return ResourceManager.GetString("faletxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com {
            get {
                object obj = ResourceManager.GetObject("pngwing_com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
